# Generated by Django 4.2.6 on 2023-11-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_remove_address_state_address_location_and_more'),
        ('cop', '0002_cop_countie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cop',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_cop', to='address.address', verbose_name='Endereço da delegacia'),
        ),
    ]
