# Generated by Django 4.2.6 on 2023-11-30 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('name', models.CharField(choices=[('nao_informado', 'Não informado'), ('incendio', 'Incêndio'), ('briga', 'Briga'), ('invasao_armada', 'Invasão Armada')], max_length=20)),
                ('code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'type_incident',
            },
        ),
    ]
