# Generated by Django 4.2.6 on 2023-11-30 23:03

from django.db import migrations
import uuid

def insert_type_incident_choices(apps, schema_editor):
    Type_Incident = apps.get_model('type_incident', 'Type_Incident')

    # Dados com UUIDs específicos
    data = [
        {'id': uuid.UUID('228996cd-aef9-42e9-b1ef-08b89132a37d'), 'code': 'Não informado', 'name': 'nao_informado'},
        {'id': uuid.UUID('22293e77-ed58-465a-9fe6-280532127455'), 'code': 'Incêndio', 'name': 'incendio'},
        {'id': uuid.UUID('6c047bb7-0121-480e-a3e0-0675a6cde28c'), 'code': 'Briga', 'name': 'briga'},
        {'id': uuid.UUID('6d1f8f1e-0d9d-4a1e-a373-658aff639fd7'), 'code': 'Invasão Armada', 'name': 'invasao_armada'},
    ]

    for entry in data:
        Type_Incident.objects.create(
            id=entry['id'],
            name=entry['name'],
            code=entry['code']
        )



class Migration(migrations.Migration):

    dependencies = [
        ('type_incident', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_type_incident_choices),
    ]
