# Generated by Django 4.2.6 on 2023-11-01 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('code', models.CharField(choices=[('ADMIN', 'ADMIN'), ('AGENT', 'AGENT'), ('TEACHER', 'TEACHER')], default='ADMIN', max_length=8, verbose_name='Nome da role em inglês')),
                ('name', models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('AGENTE', 'AGENTE'), ('PROFESSOR', 'PROFESSOR')], default='ADMINISTRADOR', verbose_name='Nome da role em portugês')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
