# Generated by Django 4.2.6 on 2023-11-30 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('type_incident', '0001_initial'),
        ('cop', '0003_alter_cop_address'),
        ('school', '0004_alter_school_address_alter_school_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('description', models.TextField(null=True, verbose_name='Descrição do alerta')),
                ('problem_solving', models.TextField(max_length=500, verbose_name='Resolução do problema')),
                ('status', models.CharField(choices=[('ajuda_caminho', 'Ajuda a Caminho'), ('ocorrencia_resolvida', 'Ocorrência Resolvida'), ('ocorrencia_iniciada', 'Ocorrência iniciada')], max_length=50)),
                ('concluded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concluded_by_button', to=settings.AUTH_USER_MODEL)),
                ('cop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cop_button', to='cop.cop')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_button', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_button', to='school.school')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_button', to=settings.AUTH_USER_MODEL)),
                ('type_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_incident_button', to='type_incident.type_incident')),
                ('updater_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_by_button', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'button',
            },
        ),
    ]
