# Generated by Django 4.2.6 on 2023-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_alter_button_concluded_by_alter_button_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição do alerta'),
        ),
    ]
