# Generated by Django 4.2.6 on 2024-01-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0003_auto_20240111_1951'),
        ('button', '0003_alter_button_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='countie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countie_button', to='counties.counties', verbose_name='Município do alerta'),
        ),
    ]
