# Generated by Django 4.2.6 on 2023-10-31 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_deleted_by'),
        ('users', '0002_baseuser_created_by_baseuser_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='whatsapp',
            field=models.CharField(null=True, verbose_name='whatsapp'),
        ),
        migrations.CreateModel(
            name='BaseUserSchool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Escola do usuario',
                'verbose_name_plural': 'Escolas dos usuarios',
                'db_table': 'users_base_user_school',
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='school',
            field=models.ManyToManyField(related_name='users_school', related_query_name='school_user', through='users.BaseUserSchool', to='school.school'),
        ),
    ]
