# Generated by Django 4.2.6 on 2023-11-01 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('users', '0003_alter_baseuser_phone_alter_baseuser_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserRoles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.roles')),
            ],
            options={
                'verbose_name': 'Função do usuario',
                'verbose_name_plural': 'Função dos usuarios',
                'db_table': 'users_base_user_roles',
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.ManyToManyField(related_name='users_role', related_query_name='role_user', through='users.BaseUserRoles', to='role.roles'),
        ),
    ]
