# Generated by Django 4.2.6 on 2023-11-03 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0001_initial'),
        ('users', '0004_baseuserroles_baseuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserCop',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cop.cop')),
            ],
            options={
                'verbose_name': 'Delegacia do usuario',
                'verbose_name_plural': 'Delegacias dos usuarios',
                'db_table': 'users_base_user_cop',
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='cop',
            field=models.ManyToManyField(related_name='users_cop', related_query_name='cop_user', through='users.BaseUserCop', to='cop.cop'),
        ),
    ]
