# Generated by Django 4.2.6 on 2023-11-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseusercop_baseuser_cop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome completo do usuário'),
        ),
    ]
