# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_baseuser_first_name_remove_baseuser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='cop',
            new_name='cops',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='role',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='school',
            new_name='schools',
        ),
    ]
