# Generated by Django 4.2.6 on 2023-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('name', models.CharField(max_length=500, verbose_name='Nome da escola')),
                ('address', models.CharField(max_length=500, verbose_name='Endereço da escola')),
                ('geolocation', models.CharField(max_length=500, verbose_name='Geolocalização da escola')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schools', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_schools', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
