# Generated by Django 4.2.6 on 2023-11-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0002_auto_20231111_1829'),
        ('school', '0002_alter_school_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='countie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countie_school', to='counties.counties', verbose_name='Município da escola'),
        ),
    ]
