# Generated by Django 4.2.6 on 2023-11-15 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
        ('school', '0003_school_countie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_school', to='address.address', verbose_name='Endereço da escola'),
        ),
        migrations.AlterField(
            model_name='school',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_schools', to=settings.AUTH_USER_MODEL),
        ),
    ]
