# Generated by Django 4.2.6 on 2023-11-15 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('zipCode', models.CharField(max_length=10, verbose_name='CEP')),
                ('district', models.CharField(max_length=150, verbose_name='Bairro')),
                ('uf', models.CharField(max_length=2, verbose_name='Sigla do estado')),
                ('state', models.CharField(max_length=100, verbose_name='Nome do estado')),
                ('publicArea', models.CharField(max_length=250, verbose_name='Logradouro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
