# Generated by Django 4.2.6 on 2023-11-11 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('name', models.CharField(max_length=500, verbose_name='Nome do município')),
                ('code', models.CharField(max_length=500, verbose_name='Código unico')),
            ],
            options={
                'db_table': 'counties',
            },
        ),
    ]
