# Generated by Django 4.2.6 on 2023-11-11 21:29

from django.db import migrations
from apps.counties.models import Counties
import json 
from panicButton.settings import BASE_SOCKET_URL
import socketio

def create_counties(apps, schema_editor):
    data = open('resource/data/counties.json')
    counties = json.load(data)
    
    for countie in counties:
        countie = Counties.objects.create(name=countie.get("nome"))

                   
class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_counties),
    ]
