# Generated by Django 4.2.6 on 2024-01-11 22:51

from django.db import migrations
from apps.counties.models import Counties
import json 

def create_counties(apps, schema_editor):
    data = open('resource/data/counties.json')
    counties = json.load(data)
    
    for countie in counties:
        countie = Counties.objects.create(name=countie.get("nome"))


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0002_counties_released'),
    ]

    operations = [
        migrations.RunPython(create_counties),
    ]
