# Generated by Django 4.2.6 on 2023-10-28 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('name', models.CharField()),
                ('phone', models.CharField()),
                ('whatsapp', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'educator',
            },
        ),
    ]
